//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMO {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMO.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaple Sarkar - Public Redressal Portal.
        /// </summary>
        internal static string LAapleSarkar {
            get {
                return ResourceManager.GetString("LAapleSarkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAHA GOVT. APPS.
        /// </summary>
        internal static string LApplicationList {
            get {
                return ResourceManager.GetString("LApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string LBiography {
            get {
                return ResourceManager.GetString("LBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet Ministers.
        /// </summary>
        internal static string LCabinetMinister {
            get {
                return ResourceManager.GetString("LCabinetMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string LCall {
            get {
                return ResourceManager.GetString("LCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE LANGUAGE.
        /// </summary>
        internal static string LChangeLanguage {
            get {
                return ResourceManager.GetString("LChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Justice.
        /// </summary>
        internal static string LChiefJustice {
            get {
                return ResourceManager.GetString("LChiefJustice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devendra Gangadharrao Fadnavis is the current Chief Minister of Maharashtra and President of the ‘Bharatiya Janata Party (BJP) Maharashtra Pradesh’ is a rare brand of politician who is both, erudite and popular with the masses..
        /// </summary>
        internal static string LChiefMinisterDescription {
            get {
                return ResourceManager.GetString("LChiefMinisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shri Devendra Fadnavis.
        /// </summary>
        internal static string LChiefMinisterName {
            get {
                return ResourceManager.GetString("LChiefMinisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   CHIEF MINISTER OFFICE &gt;  .
        /// </summary>
        internal static string LChiefMinisterOffice {
            get {
                return ResourceManager.GetString("LChiefMinisterOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Minister&apos;s Medical Assistance Cell.
        /// </summary>
        internal static string LChiefMinistersAssistanceCell {
            get {
                return ResourceManager.GetString("LChiefMinistersAssistanceCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Minister&apos;s Fellowship Programme.
        /// </summary>
        internal static string LCmInternshipProgram {
            get {
                return ResourceManager.GetString("LCmInternshipProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM&apos;S OFFICE.
        /// </summary>
        internal static string LCmOffice {
            get {
                return ResourceManager.GetString("LCmOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6th Floor, Main Building, Mantralaya, Dr.Madam Cama Road, Fort, Mumbai..
        /// </summary>
        internal static string LCMOfficeAddress {
            get {
                return ResourceManager.GetString("LCMOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string LCMOfficeContactUsSubmitButton {
            get {
                return ResourceManager.GetString("LCMOfficeContactUsSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chiefminister@maharashtra.gov.in.
        /// </summary>
        internal static string LCMOfficeEmail {
            get {
                return ResourceManager.GetString("LCMOfficeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022-22029214.
        /// </summary>
        internal static string LCMOfficeFaxNumber {
            get {
                return ResourceManager.GetString("LCMOfficeFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHIEF MINISTER&apos;S OFFICE (CMO).
        /// </summary>
        internal static string LCMOfficeName {
            get {
                return ResourceManager.GetString("LCMOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022-22025151.
        /// </summary>
        internal static string LCMOfficePhoneNumber1 {
            get {
                return ResourceManager.GetString("LCMOfficePhoneNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022-22025222.
        /// </summary>
        internal static string LCMOfficePhoneNumber2 {
            get {
                return ResourceManager.GetString("LCMOfficePhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Minister’s Relief Fund.
        /// </summary>
        internal static string LCmReliefsFund {
            get {
                return ResourceManager.GetString("LCmReliefsFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Chief Minister&apos;s official visit section. To attract foreign investment to Maharashtra Chief Minister has visited many countries and other places. Make in Maharashtra is one of the major initiative started by Government of Maharashtra on sidelines of Make in India initiative by Government of India..
        /// </summary>
        internal static string LCMVisitDescription {
            get {
                return ResourceManager.GetString("LCMVisitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM IN ACTION.
        /// </summary>
        internal static string LCmVisits {
            get {
                return ResourceManager.GetString("LCmVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM in Action.
        /// </summary>
        internal static string LCmVisitsTitle {
            get {
                return ResourceManager.GetString("LCmVisitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectors.
        /// </summary>
        internal static string LCollectors {
            get {
                return ResourceManager.GetString("LCollectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon....
        /// </summary>
        internal static string LComingSoon {
            get {
                return ResourceManager.GetString("LComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the CMO.
        /// </summary>
        internal static string LContactcmo {
            get {
                return ResourceManager.GetString("LContactcmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Email Address.
        /// </summary>
        internal static string LContactEmail {
            get {
                return ResourceManager.GetString("LContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Message.
        /// </summary>
        internal static string LContactMessage {
            get {
                return ResourceManager.GetString("LContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Mobile Number.
        /// </summary>
        internal static string LContactMobileNumber {
            get {
                return ResourceManager.GetString("LContactMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Name.
        /// </summary>
        internal static string LContactName {
            get {
                return ResourceManager.GetString("LContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial a Number.
        /// </summary>
        internal static string LDialNumber {
            get {
                return ResourceManager.GetString("LDialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Maharashtra.
        /// </summary>
        internal static string LDigitalMaharashtra {
            get {
                return ResourceManager.GetString("LDigitalMaharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to download the file?.
        /// </summary>
        internal static string LDownloadFile {
            get {
                return ResourceManager.GetString("LDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jalyukta Shivar - Drought-free Maharashtra.
        /// </summary>
        internal static string LDroughtFreeMaharashtra {
            get {
                return ResourceManager.GetString("LDroughtFreeMaharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Email Address..
        /// </summary>
        internal static string LEmailCheck {
            get {
                return ResourceManager.GetString("LEmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LError {
            get {
                return ResourceManager.GetString("LError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Calendar.
        /// </summary>
        internal static string LEvents {
            get {
                return ResourceManager.GetString("LEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMO.
        /// </summary>
        internal static string LExit {
            get {
                return ResourceManager.GetString("LExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string LExitApp {
            get {
                return ResourceManager.GetString("LExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid .
        /// </summary>
        internal static string LFieldIsRequired {
            get {
                return ResourceManager.GetString("LFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        internal static string LForeignVisits {
            get {
                return ResourceManager.GetString("LForeignVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Former Maharashtra Chief Ministers.
        /// </summary>
        internal static string LFormercmo {
            get {
                return ResourceManager.GetString("LFormercmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIA LIBRARY.
        /// </summary>
        internal static string LGallery {
            get {
                return ResourceManager.GetString("LGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governor.
        /// </summary>
        internal static string LGovernor {
            get {
                return ResourceManager.GetString("LGovernor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Departments.
        /// </summary>
        internal static string LGovtDepartment {
            get {
                return ResourceManager.GetString("LGovtDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string LHome {
            get {
                return ResourceManager.GetString("LHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INITIATIVES.
        /// </summary>
        internal static string LInitiatives {
            get {
                return ResourceManager.GetString("LInitiatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Honourable Chief Minister Shri Devendra Fadnavis unveiled initiatives to transform the country’s financial capital into a global financial and entertainment centre. CM said his government was looking forward to use deliberations from the upcoming conference to finetune its strategies..
        /// </summary>
        internal static string LInitiativesDescription {
            get {
                return ResourceManager.GetString("LInitiativesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiatives.
        /// </summary>
        internal static string LInitiativesTitle {
            get {
                return ResourceManager.GetString("LInitiativesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jalyukta Visits.
        /// </summary>
        internal static string LJalyuktaVisits {
            get {
                return ResourceManager.GetString("LJalyuktaVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN US.
        /// </summary>
        internal static string LJoinUs {
            get {
                return ResourceManager.GetString("LJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Minister&apos;s Internship Program is a unique opportunity for the youth of Maharashtra. For the first time, the young minds will be able to participate and work in the decision-making and implementation process of the government..
        /// </summary>
        internal static string LJoinUsDescription {
            get {
                return ResourceManager.GetString("LJoinUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us.
        /// </summary>
        internal static string LJoinUsTitle {
            get {
                return ResourceManager.GetString("LJoinUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications  Gallery.
        /// </summary>
        internal static string LMagazineGallery {
            get {
                return ResourceManager.GetString("LMagazineGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June 2015.
        /// </summary>
        internal static string LMagazineGalleryJune2015 {
            get {
                return ResourceManager.GetString("LMagazineGalleryJune2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Ahead.
        /// </summary>
        internal static string LMaharashtraAhead {
            get {
                return ResourceManager.GetString("LMaharashtraAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra CMO.
        /// </summary>
        internal static string LMaharashtraCMO {
            get {
                return ResourceManager.GetString("LMaharashtraCMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAHARASHTRA GOVERNMENT APPS.
        /// </summary>
        internal static string LMaharashtraGovernmentApps {
            get {
                return ResourceManager.GetString("LMaharashtraGovernmentApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Visit.
        /// </summary>
        internal static string LMaharashtraVisitPhotos {
            get {
                return ResourceManager.GetString("LMaharashtraVisitPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        internal static string LMaharashtraVisits {
            get {
                return ResourceManager.GetString("LMaharashtraVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make in Maharashtra.
        /// </summary>
        internal static string LMakeInMaharashtra {
            get {
                return ResourceManager.GetString("LMakeInMaharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        internal static string LMenu {
            get {
                return ResourceManager.GetString("LMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Justice.
        /// </summary>
        internal static string LMenuChiefMinister {
            get {
                return ResourceManager.GetString("LMenuChiefMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string LMenuPhotoGallery {
            get {
                return ResourceManager.GetString("LMenuPhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Releases.
        /// </summary>
        internal static string LMenuPressRelease {
            get {
                return ResourceManager.GetString("LMenuPressRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Gallery.
        /// </summary>
        internal static string LMenuVideoGallery {
            get {
                return ResourceManager.GetString("LMenuVideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LMessage {
            get {
                return ResourceManager.GetString("LMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter min. 3 and max. 300 characters in Message..
        /// </summary>
        internal static string LMessageLengthCheck {
            get {
                return ResourceManager.GetString("LMessageLengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter min. 10 and max. 15 characters in Mobile..
        /// </summary>
        internal static string LMobileNumberCheck {
            get {
                return ResourceManager.GetString("LMobileNumberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string LMonth {
            get {
                return ResourceManager.GetString("LMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More on Twitter.
        /// </summary>
        internal static string LMoreOnTwitter {
            get {
                return ResourceManager.GetString("LMoreOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyGov.
        /// </summary>
        internal static string LMyGov {
            get {
                return ResourceManager.GetString("LMyGov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter min. 3 and max. 50 characters in Name..
        /// </summary>
        internal static string LNameLengthCheck {
            get {
                return ResourceManager.GetString("LNameLengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string LNetworkError {
            get {
                return ResourceManager.GetString("LNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDS.
        /// </summary>
        internal static string LNewsFeed {
            get {
                return ResourceManager.GetString("LNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Updates.
        /// </summary>
        internal static string LNewsGallery {
            get {
                return ResourceManager.GetString("LNewsGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS UPDATES.
        /// </summary>
        internal static string LNewsUpdates {
            get {
                return ResourceManager.GetString("LNewsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Updates.
        /// </summary>
        internal static string LNewsUpdatesTitle {
            get {
                return ResourceManager.GetString("LNewsUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string LNo {
            get {
                return ResourceManager.GetString("LNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection available.
        /// </summary>
        internal static string LNoInternetConnection {
            get {
                return ResourceManager.GetString("LNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RECORDS FOUND.
        /// </summary>
        internal static string LNoRecordsFound {
            get {
                return ResourceManager.GetString("LNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string LNotification {
            get {
                return ResourceManager.GetString("LNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string LOf {
            get {
                return ResourceManager.GetString("LOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LOk {
            get {
                return ResourceManager.GetString("LOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Website.
        /// </summary>
        internal static string LPersonalWebsite {
            get {
                return ResourceManager.GetString("LPersonalWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTO GALLERY.
        /// </summary>
        internal static string LPhotoGallery {
            get {
                return ResourceManager.GetString("LPhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string LPhotoGalleryTitle {
            get {
                return ResourceManager.GetString("LPhotoGalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string LPhotos {
            get {
                return ResourceManager.GetString("LPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Releases.
        /// </summary>
        internal static string LPressClip {
            get {
                return ResourceManager.GetString("LPressClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS RELEASES.
        /// </summary>
        internal static string LPressGallery {
            get {
                return ResourceManager.GetString("LPressGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Releases.
        /// </summary>
        internal static string LPressRelease {
            get {
                return ResourceManager.GetString("LPressRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS RELEASE.
        /// </summary>
        internal static string LpressReleaseDetail {
            get {
                return ResourceManager.GetString("LpressReleaseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Service.
        /// </summary>
        internal static string LRightToService {
            get {
                return ResourceManager.GetString("LRightToService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LSearch {
            get {
                return ResourceManager.GetString("LSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Event.
        /// </summary>
        internal static string LSearchEvent {
            get {
                return ResourceManager.GetString("LSearchEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Jalyukta Visit.
        /// </summary>
        internal static string LSearchJalyuktaVisits {
            get {
                return ResourceManager.GetString("LSearchJalyuktaVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Maharashtra Visit.
        /// </summary>
        internal static string LSearchMaharashtraVisits {
            get {
                return ResourceManager.GetString("LSearchMaharashtraVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search International Visit.
        /// </summary>
        internal static string LSearchMakeinMaha {
            get {
                return ResourceManager.GetString("LSearchMakeinMaha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Photo.
        /// </summary>
        internal static string LSearchPhoto {
            get {
                return ResourceManager.GetString("LSearchPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Press Release.
        /// </summary>
        internal static string LSearchPressRelease {
            get {
                return ResourceManager.GetString("LSearchPressRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Video.
        /// </summary>
        internal static string LSearchVideo {
            get {
                return ResourceManager.GetString("LSearchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretaries.
        /// </summary>
        internal static string LSecretaries {
            get {
                return ResourceManager.GetString("LSecretaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Development.
        /// </summary>
        internal static string LSkillDevelopment {
            get {
                return ResourceManager.GetString("LSkillDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahabhag - Social Responsibility Cell.
        /// </summary>
        internal static string LSocialResponsibilityCell {
            get {
                return ResourceManager.GetString("LSocialResponsibilityCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not responding. Please try again later..
        /// </summary>
        internal static string LSomethingWentWrong {
            get {
                return ResourceManager.GetString("LSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Ministers.
        /// </summary>
        internal static string LStateMinisters {
            get {
                return ResourceManager.GetString("LStateMinisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Subject.
        /// </summary>
        internal static string LSubject {
            get {
                return ResourceManager.GetString("LSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter min. 3 and max. 100 characters in Subject..
        /// </summary>
        internal static string LSubjectLengthCheck {
            get {
                return ResourceManager.GetString("LSubjectLengthCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string LSubmit {
            get {
                return ResourceManager.GetString("LSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swachh Maharashtra.
        /// </summary>
        internal static string LSwachhMaharashtra {
            get {
                return ResourceManager.GetString("LSwachhMaharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team CMO.
        /// </summary>
        internal static string LTeamcmo {
            get {
                return ResourceManager.GetString("LTeamcmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM MAHARASHTRA.
        /// </summary>
        internal static string LTeamMaharashtra {
            get {
                return ResourceManager.GetString("LTeamMaharashtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can find out A to Z information of all the important Functionaries of Maharashtra Government..
        /// </summary>
        internal static string LTeamMaharashtraDescription {
            get {
                return ResourceManager.GetString("LTeamMaharashtraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Maharashtra.
        /// </summary>
        internal static string LTeamMaharashtraTitle {
            get {
                return ResourceManager.GetString("LTeamMaharashtraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for writing us, We will get back you as soon as possible..
        /// </summary>
        internal static string LThankYouMsg {
            get {
                return ResourceManager.GetString("LThankYouMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEET THE CHIEF MINISTER.
        /// </summary>
        internal static string LTheChiefMinister {
            get {
                return ResourceManager.GetString("LTheChiefMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet the Chief Minister.
        /// </summary>
        internal static string LTheChiefMinisterTitle {
            get {
                return ResourceManager.GetString("LTheChiefMinisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO GALLERY.
        /// </summary>
        internal static string LVideoGallery {
            get {
                return ResourceManager.GetString("LVideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Gallery.
        /// </summary>
        internal static string LVideoGalleryTitle {
            get {
                return ResourceManager.GetString("LVideoGalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string LVideos {
            get {
                return ResourceManager.GetString("LVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  VIEW ALL .
        /// </summary>
        internal static string LViewAll {
            get {
                return ResourceManager.GetString("LViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision and Mission.
        /// </summary>
        internal static string LVisionMissionOath {
            get {
                return ResourceManager.GetString("LVisionMissionOath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not responding. Please try again later..
        /// </summary>
        internal static string LWebserverNotResponding {
            get {
                return ResourceManager.GetString("LWebserverNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string LYear {
            get {
                return ResourceManager.GetString("LYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string LYes {
            get {
                return ResourceManager.GetString("LYes", resourceCulture);
            }
        }
    }
}
